// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: collegepb/college.proto

package collegepb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Mahasiswa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nama string `protobuf:"bytes,2,opt,name=nama,proto3" json:"nama,omitempty"`
}

func (x *Mahasiswa) Reset() {
	*x = Mahasiswa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collegepb_college_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mahasiswa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mahasiswa) ProtoMessage() {}

func (x *Mahasiswa) ProtoReflect() protoreflect.Message {
	mi := &file_collegepb_college_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mahasiswa.ProtoReflect.Descriptor instead.
func (*Mahasiswa) Descriptor() ([]byte, []int) {
	return file_collegepb_college_proto_rawDescGZIP(), []int{0}
}

func (x *Mahasiswa) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mahasiswa) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

// Mahasiwa
type CreateMhsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mahasiswa *Mahasiswa `protobuf:"bytes,1,opt,name=mahasiswa,proto3" json:"mahasiswa,omitempty"`
}

func (x *CreateMhsRequest) Reset() {
	*x = CreateMhsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collegepb_college_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMhsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMhsRequest) ProtoMessage() {}

func (x *CreateMhsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collegepb_college_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMhsRequest.ProtoReflect.Descriptor instead.
func (*CreateMhsRequest) Descriptor() ([]byte, []int) {
	return file_collegepb_college_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMhsRequest) GetMahasiswa() *Mahasiswa {
	if x != nil {
		return x.Mahasiswa
	}
	return nil
}

type GetMhsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mhs *Mahasiswa `protobuf:"bytes,1,opt,name=mhs,proto3" json:"mhs,omitempty"`
}

func (x *GetMhsResponse) Reset() {
	*x = GetMhsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collegepb_college_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMhsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMhsResponse) ProtoMessage() {}

func (x *GetMhsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collegepb_college_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMhsResponse.ProtoReflect.Descriptor instead.
func (*GetMhsResponse) Descriptor() ([]byte, []int) {
	return file_collegepb_college_proto_rawDescGZIP(), []int{2}
}

func (x *GetMhsResponse) GetMhs() *Mahasiswa {
	if x != nil {
		return x.Mhs
	}
	return nil
}

type EdiMhsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nama string `protobuf:"bytes,2,opt,name=nama,proto3" json:"nama,omitempty"`
}

func (x *EdiMhsRequest) Reset() {
	*x = EdiMhsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collegepb_college_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdiMhsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdiMhsRequest) ProtoMessage() {}

func (x *EdiMhsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collegepb_college_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdiMhsRequest.ProtoReflect.Descriptor instead.
func (*EdiMhsRequest) Descriptor() ([]byte, []int) {
	return file_collegepb_college_proto_rawDescGZIP(), []int{3}
}

func (x *EdiMhsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EdiMhsRequest) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

type ResultMhsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ResultMhsResponse) Reset() {
	*x = ResultMhsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collegepb_college_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultMhsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultMhsResponse) ProtoMessage() {}

func (x *ResultMhsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collegepb_college_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultMhsResponse.ProtoReflect.Descriptor instead.
func (*ResultMhsResponse) Descriptor() ([]byte, []int) {
	return file_collegepb_college_proto_rawDescGZIP(), []int{4}
}

func (x *ResultMhsResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DeleteMhsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMhsRequest) Reset() {
	*x = DeleteMhsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collegepb_college_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMhsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMhsRequest) ProtoMessage() {}

func (x *DeleteMhsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collegepb_college_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMhsRequest.ProtoReflect.Descriptor instead.
func (*DeleteMhsRequest) Descriptor() ([]byte, []int) {
	return file_collegepb_college_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMhsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_collegepb_college_proto protoreflect.FileDescriptor

var file_collegepb_college_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a,
	0x09, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x61, 0x22, 0x42,
	0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x6d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x4d, 0x61,
	0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x52, 0x09, 0x6d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73,
	0x77, 0x61, 0x22, 0x34, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x68, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x6d, 0x68, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69,
	0x73, 0x77, 0x61, 0x52, 0x03, 0x6d, 0x68, 0x73, 0x22, 0x33, 0x0a, 0x0d, 0x45, 0x64, 0x69, 0x4d,
	0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x61, 0x22, 0x2b, 0x0a,
	0x11, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x68, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x22, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x8c,
	0x02, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x40, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x68, 0x73, 0x12, 0x17, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x68, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x4d, 0x68, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x68, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x68, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x3b, 0x0a, 0x07, 0x45, 0x64, 0x69, 0x74, 0x4d, 0x68, 0x73, 0x12, 0x14, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x45, 0x64, 0x69, 0x4d, 0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x4d, 0x68, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d,
	0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x68, 0x73, 0x12, 0x14, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x45, 0x64, 0x69, 0x4d, 0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x4d, 0x68, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a,
	0x09, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_collegepb_college_proto_rawDescOnce sync.Once
	file_collegepb_college_proto_rawDescData = file_collegepb_college_proto_rawDesc
)

func file_collegepb_college_proto_rawDescGZIP() []byte {
	file_collegepb_college_proto_rawDescOnce.Do(func() {
		file_collegepb_college_proto_rawDescData = protoimpl.X.CompressGZIP(file_collegepb_college_proto_rawDescData)
	})
	return file_collegepb_college_proto_rawDescData
}

var file_collegepb_college_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_collegepb_college_proto_goTypes = []interface{}{
	(*Mahasiswa)(nil),         // 0: admin.Mahasiswa
	(*CreateMhsRequest)(nil),  // 1: admin.CreateMhsRequest
	(*GetMhsResponse)(nil),    // 2: admin.GetMhsResponse
	(*EdiMhsRequest)(nil),     // 3: admin.EdiMhsRequest
	(*ResultMhsResponse)(nil), // 4: admin.ResultMhsResponse
	(*DeleteMhsRequest)(nil),  // 5: admin.DeleteMhsRequest
	(*empty.Empty)(nil),       // 6: google.protobuf.Empty
}
var file_collegepb_college_proto_depIdxs = []int32{
	0, // 0: admin.CreateMhsRequest.mahasiswa:type_name -> admin.Mahasiswa
	0, // 1: admin.GetMhsResponse.mhs:type_name -> admin.Mahasiswa
	1, // 2: admin.AdminService.CreateMhs:input_type -> admin.CreateMhsRequest
	6, // 3: admin.AdminService.GetAllMhs:input_type -> google.protobuf.Empty
	3, // 4: admin.AdminService.EditMhs:input_type -> admin.EdiMhsRequest
	3, // 5: admin.AdminService.DeleteMhs:input_type -> admin.EdiMhsRequest
	4, // 6: admin.AdminService.CreateMhs:output_type -> admin.ResultMhsResponse
	2, // 7: admin.AdminService.GetAllMhs:output_type -> admin.GetMhsResponse
	4, // 8: admin.AdminService.EditMhs:output_type -> admin.ResultMhsResponse
	4, // 9: admin.AdminService.DeleteMhs:output_type -> admin.ResultMhsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_collegepb_college_proto_init() }
func file_collegepb_college_proto_init() {
	if File_collegepb_college_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collegepb_college_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mahasiswa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collegepb_college_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMhsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collegepb_college_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMhsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collegepb_college_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdiMhsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collegepb_college_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultMhsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collegepb_college_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMhsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collegepb_college_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collegepb_college_proto_goTypes,
		DependencyIndexes: file_collegepb_college_proto_depIdxs,
		MessageInfos:      file_collegepb_college_proto_msgTypes,
	}.Build()
	File_collegepb_college_proto = out.File
	file_collegepb_college_proto_rawDesc = nil
	file_collegepb_college_proto_goTypes = nil
	file_collegepb_college_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	CreateMhs(ctx context.Context, in *CreateMhsRequest, opts ...grpc.CallOption) (*ResultMhsResponse, error)
	GetAllMhs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (AdminService_GetAllMhsClient, error)
	EditMhs(ctx context.Context, in *EdiMhsRequest, opts ...grpc.CallOption) (*ResultMhsResponse, error)
	DeleteMhs(ctx context.Context, in *EdiMhsRequest, opts ...grpc.CallOption) (*ResultMhsResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) CreateMhs(ctx context.Context, in *CreateMhsRequest, opts ...grpc.CallOption) (*ResultMhsResponse, error) {
	out := new(ResultMhsResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/CreateMhs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetAllMhs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (AdminService_GetAllMhsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AdminService_serviceDesc.Streams[0], "/admin.AdminService/GetAllMhs", opts...)
	if err != nil {
		return nil, err
	}
	x := &adminServiceGetAllMhsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AdminService_GetAllMhsClient interface {
	Recv() (*GetMhsResponse, error)
	grpc.ClientStream
}

type adminServiceGetAllMhsClient struct {
	grpc.ClientStream
}

func (x *adminServiceGetAllMhsClient) Recv() (*GetMhsResponse, error) {
	m := new(GetMhsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *adminServiceClient) EditMhs(ctx context.Context, in *EdiMhsRequest, opts ...grpc.CallOption) (*ResultMhsResponse, error) {
	out := new(ResultMhsResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/EditMhs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteMhs(ctx context.Context, in *EdiMhsRequest, opts ...grpc.CallOption) (*ResultMhsResponse, error) {
	out := new(ResultMhsResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/DeleteMhs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	CreateMhs(context.Context, *CreateMhsRequest) (*ResultMhsResponse, error)
	GetAllMhs(*empty.Empty, AdminService_GetAllMhsServer) error
	EditMhs(context.Context, *EdiMhsRequest) (*ResultMhsResponse, error)
	DeleteMhs(context.Context, *EdiMhsRequest) (*ResultMhsResponse, error)
}

// UnimplementedAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (*UnimplementedAdminServiceServer) CreateMhs(context.Context, *CreateMhsRequest) (*ResultMhsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMhs not implemented")
}
func (*UnimplementedAdminServiceServer) GetAllMhs(*empty.Empty, AdminService_GetAllMhsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllMhs not implemented")
}
func (*UnimplementedAdminServiceServer) EditMhs(context.Context, *EdiMhsRequest) (*ResultMhsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditMhs not implemented")
}
func (*UnimplementedAdminServiceServer) DeleteMhs(context.Context, *EdiMhsRequest) (*ResultMhsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMhs not implemented")
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_CreateMhs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMhsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateMhs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/CreateMhs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateMhs(ctx, req.(*CreateMhsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetAllMhs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).GetAllMhs(m, &adminServiceGetAllMhsServer{stream})
}

type AdminService_GetAllMhsServer interface {
	Send(*GetMhsResponse) error
	grpc.ServerStream
}

type adminServiceGetAllMhsServer struct {
	grpc.ServerStream
}

func (x *adminServiceGetAllMhsServer) Send(m *GetMhsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AdminService_EditMhs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EdiMhsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).EditMhs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/EditMhs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).EditMhs(ctx, req.(*EdiMhsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteMhs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EdiMhsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteMhs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/DeleteMhs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteMhs(ctx, req.(*EdiMhsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMhs",
			Handler:    _AdminService_CreateMhs_Handler,
		},
		{
			MethodName: "EditMhs",
			Handler:    _AdminService_EditMhs_Handler,
		},
		{
			MethodName: "DeleteMhs",
			Handler:    _AdminService_DeleteMhs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllMhs",
			Handler:       _AdminService_GetAllMhs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "collegepb/college.proto",
}
